name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies    
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest > test_results.txt
        
    - name: Create build artifacts
      run: mkdir -p build

    - name: Copy test results
      run: cp test_results.txt build/test_results.txt

    - name: Updload build artifacts
      uses: actions/upload-artifacts@v2
      with:
        name: build-results
        path: build/
